### ISSUE TITLE
Unable to update version number, GitHub has completed, version update cannot be seen in Arduino Manager,

### ISSUE THREAD

**Issue by gooddisplayshare** [arduino/libraries-repository-engine#287]
The Arduino library version has been updated from v1.0.1 to v1.0.2. The library has been updated and the release version has been updated. However, the library manager in Arduino software is still v1.0.1. 
Could you please find the reason? Thank you~

https://github.com/gooddisplayshare/ESP32epd

**Comment by per1234** [comment]
I see there is an entry for `library.properties` in the `.gitignore` file:

https://github.com/gooddisplayshare/ESP32epd/blob/2dde2a694feabb5c2b90214634b5605395ac2037/.gitignore#L2

```text
library.properties
```

There was a bug in the [`github.com/go-git/go-git`](https://github.com/go-git/go-git) Go module we use to work with the Git repository that would result in the ignored file being left in a "dirty" state after checkout: https://github.com/go-git/go-git/issues/819. That bug was fixed by https://github.com/go-git/go-git/commit/0377d0627fa4e32a576634f441e72153807e395a. https://github.com/arduino/libraries-repository-engine/pull/286 updated the `github.com/go-git/go-git` dependency to a version that contains the fix (https://github.com/go-git/go-git/pull/485), and that update was put into production with the [1.1.6](https://github.com/arduino/libraries-repository-engine/releases/tag/v1.1.6) release of **libraries-repository-engine**.
